"""Generate 1-bit bitmap fonts with Vietnamese coverage for the Pocketmate LCD.

Usage: python3 tools/gen_font.py            (writes firmware/main/fonts.c)
Requires Pillow and Noto Sans Bold (fonts-noto-core on Debian/Ubuntu).
The generated file is committed, so the firmware build does not need Pillow.
"""
import sys
from pathlib import Path
from PIL import Image, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FONT_FILE = "/usr/share/fonts/truetype/noto/NotoSans-Bold.ttf"
SIZES = {"font_small": 18, "font_medium": 26, "font_large": 44}

# ASCII, Latin-1 letters, Vietnamese extensions, a few symbols and arrows.
RANGES = [(0x20, 0x7E), (0xA0, 0xFF), (0x102, 0x103), (0x110, 0x111),
          (0x128, 0x129), (0x168, 0x169), (0x1A0, 0x1B0), (0x1EA0, 0x1EF9),
          (0x2013, 0x2014), (0x2018, 0x2019), (0x201C, 0x201D), (0x2022, 0x2022),
          (0x2026, 0x2026), (0x2190, 0x2193), (0x2196, 0x2199), (0x21A9, 0x21AA)]


def glyphs(font, size):
    ascent, descent = font.getmetrics()
    out = []
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            ch = chr(cp)
            advance = round(font.getlength(ch))
            bbox = font.getbbox(ch)  # (x0, y0, x1, y1) relative to origin at ascent line
            if bbox is None or bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
                out.append((cp, advance, 0, 0, 0, 0, b""))
                continue
            x0, y0, x1, y1 = bbox
            w, h = x1 - x0, y1 - y0
            img = Image.new("L", (w, h), 0)
            # Draw so that glyph bbox lands at image origin.
            from PIL import ImageDraw
            ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255)
            px = img.load()
            rows = []
            for y in range(h):
                bits = 0
                for x in range(w):
                    if px[x, y] >= 110:
                        bits |= 1 << (7 - (x % 8))
                    if x % 8 == 7 or x == w - 1:
                        rows.append(bits)
                        bits = 0
            out.append((cp, advance, w, h, x0, y0, bytes(rows)))
    return ascent, descent, out


def main():
    lines = ['/* Generated by tools/gen_font.py from Noto Sans Bold (OFL 1.1). Do not edit. */',
             '#include "gfx.h"', '']
    for name, size in SIZES.items():
        font = ImageFont.truetype(FONT_FILE, size)
        ascent, descent, gl = glyphs(font, size)
        data = bytearray()
        entries = []
        for cp, adv, w, h, xo, yo, bits in gl:
            entries.append(f"    {{{cp:#06x}, {adv}, {w}, {h}, {xo}, {yo}, {len(data)}}},")
            data += bits
        lines.append(f"static const uint8_t {name}_bits[] = {{")
        for i in range(0, len(data), 24):
            lines.append("    " + ",".join(f"{b:#04x}" for b in data[i:i + 24]) + ",")
        lines.append("};")
        lines.append(f"static const gfx_glyph_t {name}_glyphs[] = {{")
        lines += entries
        lines.append("};")
        lines.append(f"const gfx_font_t {name} = {{{ascent + descent}, {ascent}, "
                     f"{len(entries)}, {name}_glyphs, {name}_bits}};")
        lines.append("")
        print(f"{name}: {size}px, {len(entries)} glyphs, {len(data)} bytes", file=sys.stderr)
    (ROOT / "firmware/main/fonts.c").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
